name: phpDocumentor

on:
  push:
    branches: [ main ]

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3
      - name: Commit docs
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git checkout -b docs/main
          git add docs/api
          git reset docs/api/.cache
          git commit -m "phpdoc: update build" || echo "No changes to commit"
          git push --set-upstream origin docs/main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: docs/main
          base: main
          commit-message: "docs: update"
          delete-branch: true
      - name: 'Merge doc pull request'
        uses: kalgurn/merge-pr-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: "conduit-innovation"
          repo: "gorilla-claw"
          pull_number: ${{ steps.cpr.outputs.pull-request-number }}
      