name: phpDocumentor

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: docs/main
          base: main
          commit-message: "docs: update"
          delete-branch: true
          title: "auto: docs build"
          body: |
            Generated documentation via phpdoc on merge
          labels: "auto,auto-doc"
      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: merge
          repo: conduit-innovation/gorilla-claw
      