name: phpDocumentor

on:
  push:
    branches: [ main ]

jobs:
  phpdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run phpdoc
        run: |
          docker run --rm -v $(pwd):/data phpdoc/phpdoc:3
      - name: Commit docs
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git checkout -b docs/main
          git push --set-upstream origin docs/main
          git add docs/api -f
          git reset docs/api/.cache
          git commit -m "phpdoc: update build" || echo "No changes to commit"
          git push
          git checkout origin/main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: docs/main
          commit-message: "docs: update"
          delete-branch: true